
# 注册中心地址，可以是zk，也可以是redis
registryAddress=zookeeper://10.16.2.30:2181

# JobTracker的监听端口
listenPort=3502

# 集群名称
clusterName=lts_cluster

# LTS业务日志, 可选值 console, mysql, mongo
configs.job.logger=mysql

# zk客户端，可选值 zkclient, curator
configs.zk.client=zkclient

# 监控中心，即LTS-Admin地址
configs.lts.monitor.url=http://10.16.2.33:8086

# ---------以下是任务队列配置-----------
# 任务队列，可选值 mysql, mongo
configs.job.queue=mysql

# ------ mysql作为任务队列 ------
configs.jdbc.url=jdbc:mysql://10.16.27.146:3306/lts
configs.jdbc.username=dbagover
configs.jdbc.password=lqsym_A0c5
